---
title: "Quadvariate Viz"
---

```{r}
#| message: false
#| warning: false
#| code-fold: true
library(tidyverse)
library(mosaic)
library(fivethirtyeight)
library(ggplot2)
```

```{r}
#| code-fold: true
data(bechdel)
new_bechdel <- bechdel |>
  mutate(clean_test = factor(clean_test, c("nowomen", "notalk", "men", "dubious", "ok"))) |>
  mutate(half_decades = cut(year, breaks = seq(1969, 2014, by = 5)))
```

```{r, fig.cap = "Created by Madeleine Heafey"}
#| code-fold: true
ggplot(new_bechdel, aes(x = half_decades, fill = clean_test)) +
  geom_bar() +
  labs(title = "Number of Films Passing Bechdel Test by Half Decade and Degree of Passing", fill = "Degree of Passing", y = "Number of Movies", x = "Half Decades", caption = "Created 2025, data from fivethirtyeight.com") +
  facet_wrap(~binary) +
  theme(panel.spacing = unit(3, "lines"), axis.text.x=element_text(color=c("black","transparent","transparent","transparent","transparent","transparent","transparent", "transparent", "black")))
```
