---
title: "Spatial Viz"
---

```{r}
#| message: false
#| code-fold: true
# Load required libraries
library(tidyverse)
library(openintro)
library(mosaic)
library(maps)
library(leaflet)
library(ggplot2)
```

```{r}
#| code-fold: true
# Import starbucks location data
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")
```

```{r}
#| code-fold: true
starbucks_us_by_state <- starbucks |>
  filter(Country == "US") |>
  count(State.Province) |>
  mutate(state_name = str_to_lower(abbr2state(State.Province)))
```

```{r}
#| message: false
#| warning: false
#| code-fold: true
census_pop_est_2018 <- read_csv("https://mac-stat.github.io/data/us_census_2018_state_pop_est.csv") |>
  separate(state, into = c("dot", "state"), extra = "merge") |>
  select(-dot) |>
  mutate(state = str_to_lower(state))

starbucks_with_2018_pop_est <-
  starbucks_us_by_state |>
  left_join(census_pop_est_2018,
    by = c("state_name" = "state")
  ) |>
  mutate(starbucks_per_10000 = (n / est_pop_2018) * 10000)
```

```{r}
#| code-fold: true
#filtering for only Starbucks in contiguous US
starbucks_cma <- starbucks |> 
  filter(Country %in% c('US'), State.Province != "AK", State.Province != "HI")
```

```{r, fig.cap = "Created by Madeleine Heafey"}
#| code-fold: true
states_map <- map_data("state")

#creating choropleth map + points for each starbucks
ggplot(starbucks_with_2018_pop_est, aes(map_id = state_name, fill = starbucks_per_10000)) +
  geom_map(map = states_map) +
  geom_point(
    data = starbucks_cma,
    aes(x = Longitude, y = Latitude),
    size = 0.3,
    alpha = 0.2,
    color = "#09402c",
    inherit.aes = FALSE
  ) +
  scale_fill_gradient(low = "white", high = "#006241", name = "Starbucks per 1000") +
  labs(title = "Plot of Starbucks per 1000 people across contiguous US", caption = "Created 2025, data from Danny Kaplan") +
  theme_map()

```
